services:
  backend1:
    build: 
      context: ./backend1
    container_name: backend1
    ports:
      - "3000:3000"
  backend2:
    build: 
      context: ./backend2
    container_name: backend2
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend1
      - backend2
